/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.JOptionPane;
import views.ajuda.FrmSobre;
import views.atendimentos.FrmAtendimentos;
import views.atendimentos.FrmTipoAtendimento;
import views.cadastros.FrmClientes;
import views.cadastros.FrmEnderecoCliente;
import views.cadastros.FrmEnderecoFornecedor;
import views.cadastros.FrmFornecedores;
import views.cadastros.FrmPets;
import views.cadastros.FrmProdutos;
import views.consultas.FrmEnderecosCliente;
import views.consultas.FrmEnderecosFornecedor;
import views.consultas.FrmVendas;
import views.estoque.FrmEstoque;
import views.financeiro.FrmConsultaDeSaldos;
import views.financeiro.FrmConsultaValoresAPagar;
import views.financeiro.FrmConsultaValoresAReceber;
import views.reposicoes.FrmNovaReposicao;
import views.vendas.FrmNovaVenda;

/**
 *
 * @author luansinh0
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JmiConsultas_Pets = new javax.swing.JMenu();
        JmiConsultas_Clientes = new javax.swing.JMenuItem();
        JmiPets = new javax.swing.JMenuItem();
        JmiConsultas_Fornecedores = new javax.swing.JMenuItem();
        JmiConsultas_Produtos = new javax.swing.JMenuItem();
        JmiConsultas_Vendas = new javax.swing.JMenuItem();
        JmiConsultas_Atendimentos = new javax.swing.JMenuItem();
        JmConsultas_Enderecos = new javax.swing.JMenu();
        JmiConsultas_Enderecos_EnderecosCliente = new javax.swing.JMenuItem();
        JmiConsultas_Enderecos_EnderecosFornecedores = new javax.swing.JMenuItem();
        JmCadastros = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        JmiCadastros_Clientes_NovoCliente = new javax.swing.JMenuItem();
        JmiCadastros_Clientes_NovoPet = new javax.swing.JMenuItem();
        JmiCadastros_Clientes_NovoEndereco = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JmiCadastros_Fornecedores_NovoFornecedor = new javax.swing.JMenuItem();
        JmiCadastros_Fornecedores_NovoEndereco = new javax.swing.JMenuItem();
        JmiCadastros_Produtos = new javax.swing.JMenuItem();
        JmAtendimentos = new javax.swing.JMenu();
        JmiAtendimentos_NovoAtendimento = new javax.swing.JMenuItem();
        JmiAtendimentos_NovoTipoAtendimento = new javax.swing.JMenuItem();
        JmVendas = new javax.swing.JMenu();
        JmiVendas_NovaVenda = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        JmiReposicoes_NovaReposicacoDeProdutos = new javax.swing.JMenuItem();
        JmEstoque = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        JmiFinanceiro_ValorAReceber = new javax.swing.JMenuItem();
        JmiFinanceiro_ValoresAPagar = new javax.swing.JMenuItem();
        JmiFinanceiro_ConsultaDeSaldos = new javax.swing.JMenuItem();
        JmAjuda = new javax.swing.JMenu();
        JmiAjuda_Sobre = new javax.swing.JMenuItem();
        JmiAjuda_Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.red);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        JmiConsultas_Pets.setText("Consultas");

        JmiConsultas_Clientes.setText("Clientes");
        JmiConsultas_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiConsultas_ClientesActionPerformed(evt);
            }
        });
        JmiConsultas_Pets.add(JmiConsultas_Clientes);

        JmiPets.setText("Pets");
        JmiPets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiPetsActionPerformed(evt);
            }
        });
        JmiConsultas_Pets.add(JmiPets);

        JmiConsultas_Fornecedores.setText("Fornecedores");
        JmiConsultas_Fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiConsultas_FornecedoresActionPerformed(evt);
            }
        });
        JmiConsultas_Pets.add(JmiConsultas_Fornecedores);

        JmiConsultas_Produtos.setText("Produtos");
        JmiConsultas_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiConsultas_ProdutosActionPerformed(evt);
            }
        });
        JmiConsultas_Pets.add(JmiConsultas_Produtos);

        JmiConsultas_Vendas.setText("Vendas");
        JmiConsultas_Vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiConsultas_VendasActionPerformed(evt);
            }
        });
        JmiConsultas_Pets.add(JmiConsultas_Vendas);

        JmiConsultas_Atendimentos.setText("Atendimentos");
        JmiConsultas_Atendimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiConsultas_AtendimentosActionPerformed(evt);
            }
        });
        JmiConsultas_Pets.add(JmiConsultas_Atendimentos);

        JmConsultas_Enderecos.setText("Endereços");

        JmiConsultas_Enderecos_EnderecosCliente.setText("Endereços de cliente...");
        JmiConsultas_Enderecos_EnderecosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiConsultas_Enderecos_EnderecosClienteActionPerformed(evt);
            }
        });
        JmConsultas_Enderecos.add(JmiConsultas_Enderecos_EnderecosCliente);

        JmiConsultas_Enderecos_EnderecosFornecedores.setText("Endereços de fornecedores...");
        JmiConsultas_Enderecos_EnderecosFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiConsultas_Enderecos_EnderecosFornecedoresActionPerformed(evt);
            }
        });
        JmConsultas_Enderecos.add(JmiConsultas_Enderecos_EnderecosFornecedores);

        JmiConsultas_Pets.add(JmConsultas_Enderecos);

        jMenuBar1.add(JmiConsultas_Pets);

        JmCadastros.setText("Cadastros");

        jMenu1.setText("Clientes");

        JmiCadastros_Clientes_NovoCliente.setText("Novo cliente...");
        JmiCadastros_Clientes_NovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiCadastros_Clientes_NovoClienteActionPerformed(evt);
            }
        });
        jMenu1.add(JmiCadastros_Clientes_NovoCliente);

        JmiCadastros_Clientes_NovoPet.setText("Novo pet...");
        JmiCadastros_Clientes_NovoPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiCadastros_Clientes_NovoPetActionPerformed(evt);
            }
        });
        jMenu1.add(JmiCadastros_Clientes_NovoPet);

        JmiCadastros_Clientes_NovoEndereco.setText("Novo endereço...");
        JmiCadastros_Clientes_NovoEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiCadastros_Clientes_NovoEnderecoActionPerformed(evt);
            }
        });
        jMenu1.add(JmiCadastros_Clientes_NovoEndereco);

        JmCadastros.add(jMenu1);

        jMenu2.setText("Fornecedores");

        JmiCadastros_Fornecedores_NovoFornecedor.setText("Novo fornecedor...");
        JmiCadastros_Fornecedores_NovoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiCadastros_Fornecedores_NovoFornecedorActionPerformed(evt);
            }
        });
        jMenu2.add(JmiCadastros_Fornecedores_NovoFornecedor);

        JmiCadastros_Fornecedores_NovoEndereco.setText("Novo endereço...");
        JmiCadastros_Fornecedores_NovoEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiCadastros_Fornecedores_NovoEnderecoActionPerformed(evt);
            }
        });
        jMenu2.add(JmiCadastros_Fornecedores_NovoEndereco);

        JmCadastros.add(jMenu2);

        JmiCadastros_Produtos.setText("Produtos");
        JmiCadastros_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiCadastros_ProdutosActionPerformed(evt);
            }
        });
        JmCadastros.add(JmiCadastros_Produtos);

        jMenuBar1.add(JmCadastros);

        JmAtendimentos.setText("Atendimentos");
        JmAtendimentos.setToolTipText("");

        JmiAtendimentos_NovoAtendimento.setText("Novo atendimento...");
        JmiAtendimentos_NovoAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiAtendimentos_NovoAtendimentoActionPerformed(evt);
            }
        });
        JmAtendimentos.add(JmiAtendimentos_NovoAtendimento);

        JmiAtendimentos_NovoTipoAtendimento.setText("Novo tipo de atendimento...");
        JmiAtendimentos_NovoTipoAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiAtendimentos_NovoTipoAtendimentoActionPerformed(evt);
            }
        });
        JmAtendimentos.add(JmiAtendimentos_NovoTipoAtendimento);

        jMenuBar1.add(JmAtendimentos);

        JmVendas.setText("Vendas");

        JmiVendas_NovaVenda.setText("Nova venda...");
        JmiVendas_NovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiVendas_NovaVendaActionPerformed(evt);
            }
        });
        JmVendas.add(JmiVendas_NovaVenda);

        jMenuBar1.add(JmVendas);

        jMenu3.setText("Reposições");

        JmiReposicoes_NovaReposicacoDeProdutos.setText("Nova reposição de produtos...");
        JmiReposicoes_NovaReposicacoDeProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiReposicoes_NovaReposicacoDeProdutosActionPerformed(evt);
            }
        });
        jMenu3.add(JmiReposicoes_NovaReposicacoDeProdutos);

        jMenuBar1.add(jMenu3);

        JmEstoque.setText("Estoque");

        jMenuItem1.setText("Consulta do estoque...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        JmEstoque.add(jMenuItem1);

        jMenuBar1.add(JmEstoque);

        jMenu4.setText("Financeiro");

        JmiFinanceiro_ValorAReceber.setText("Valores a receber...");
        JmiFinanceiro_ValorAReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiFinanceiro_ValorAReceberActionPerformed(evt);
            }
        });
        jMenu4.add(JmiFinanceiro_ValorAReceber);

        JmiFinanceiro_ValoresAPagar.setText("Valores a pagar...");
        JmiFinanceiro_ValoresAPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiFinanceiro_ValoresAPagarActionPerformed(evt);
            }
        });
        jMenu4.add(JmiFinanceiro_ValoresAPagar);

        JmiFinanceiro_ConsultaDeSaldos.setText("Consulta de saldos...");
        JmiFinanceiro_ConsultaDeSaldos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiFinanceiro_ConsultaDeSaldosActionPerformed(evt);
            }
        });
        jMenu4.add(JmiFinanceiro_ConsultaDeSaldos);

        jMenuBar1.add(jMenu4);

        JmAjuda.setText("Ajuda");

        JmiAjuda_Sobre.setText("Sobre");
        JmiAjuda_Sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiAjuda_SobreActionPerformed(evt);
            }
        });
        JmAjuda.add(JmiAjuda_Sobre);

        JmiAjuda_Sair.setText("Sair");
        JmiAjuda_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmiAjuda_SairActionPerformed(evt);
            }
        });
        JmAjuda.add(JmiAjuda_Sair);

        jMenuBar1.add(JmAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitApplication() {
        int sair = JOptionPane.showConfirmDialog(null, "Confirmar saída?");
        if (sair == 0) {
            dispose();
        }
    }
    
    private void JmiAjuda_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiAjuda_SairActionPerformed
        exitApplication();
    }//GEN-LAST:event_JmiAjuda_SairActionPerformed

    private void JmiAjuda_SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiAjuda_SobreActionPerformed
        new FrmSobre().setVisible(true);
    }//GEN-LAST:event_JmiAjuda_SobreActionPerformed

    private void JmiCadastros_Clientes_NovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiCadastros_Clientes_NovoClienteActionPerformed
        new FrmClientes().setVisible(true);
    }//GEN-LAST:event_JmiCadastros_Clientes_NovoClienteActionPerformed

    private void JmiCadastros_Clientes_NovoPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiCadastros_Clientes_NovoPetActionPerformed
        new FrmPets().setVisible(true);
    }//GEN-LAST:event_JmiCadastros_Clientes_NovoPetActionPerformed

    private void JmiCadastros_Clientes_NovoEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiCadastros_Clientes_NovoEnderecoActionPerformed
        new FrmEnderecoCliente().setVisible(true);
    }//GEN-LAST:event_JmiCadastros_Clientes_NovoEnderecoActionPerformed

    private void JmiCadastros_Fornecedores_NovoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiCadastros_Fornecedores_NovoFornecedorActionPerformed
        new FrmFornecedores().setVisible(true);
    }//GEN-LAST:event_JmiCadastros_Fornecedores_NovoFornecedorActionPerformed

    private void JmiCadastros_Fornecedores_NovoEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiCadastros_Fornecedores_NovoEnderecoActionPerformed
        new FrmEnderecoFornecedor().setVisible(true);
    }//GEN-LAST:event_JmiCadastros_Fornecedores_NovoEnderecoActionPerformed

    private void JmiAtendimentos_NovoAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiAtendimentos_NovoAtendimentoActionPerformed
        new FrmAtendimentos().setVisible(true);
    }//GEN-LAST:event_JmiAtendimentos_NovoAtendimentoActionPerformed

    private void JmiCadastros_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiCadastros_ProdutosActionPerformed
        new FrmProdutos().setVisible(true);
    }//GEN-LAST:event_JmiCadastros_ProdutosActionPerformed

    private void JmiAtendimentos_NovoTipoAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiAtendimentos_NovoTipoAtendimentoActionPerformed
        new FrmTipoAtendimento().setVisible(true);
    }//GEN-LAST:event_JmiAtendimentos_NovoTipoAtendimentoActionPerformed

    private void JmiConsultas_AtendimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiConsultas_AtendimentosActionPerformed
        new views.consultas.FrmAtendimentos().setVisible(true);
    }//GEN-LAST:event_JmiConsultas_AtendimentosActionPerformed

    private void JmiConsultas_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiConsultas_ClientesActionPerformed
        new views.consultas.FrmClientes().setVisible(true);
    }//GEN-LAST:event_JmiConsultas_ClientesActionPerformed

    private void JmiPetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiPetsActionPerformed
       new views.consultas.FrmPets().setVisible(true);
    }//GEN-LAST:event_JmiPetsActionPerformed

    private void JmiConsultas_FornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiConsultas_FornecedoresActionPerformed
        new views.consultas.FrmFornecedores().setVisible(true);
    }//GEN-LAST:event_JmiConsultas_FornecedoresActionPerformed

    private void JmiConsultas_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiConsultas_ProdutosActionPerformed
        new views.consultas.FrmProdutos().setVisible(true);
    }//GEN-LAST:event_JmiConsultas_ProdutosActionPerformed

    private void JmiConsultas_VendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiConsultas_VendasActionPerformed
        new FrmVendas().setVisible(true);
    }//GEN-LAST:event_JmiConsultas_VendasActionPerformed

    private void JmiConsultas_Enderecos_EnderecosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiConsultas_Enderecos_EnderecosClienteActionPerformed
        new FrmEnderecosCliente().setVisible(true);
    }//GEN-LAST:event_JmiConsultas_Enderecos_EnderecosClienteActionPerformed

    private void JmiConsultas_Enderecos_EnderecosFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiConsultas_Enderecos_EnderecosFornecedoresActionPerformed
        new FrmEnderecosFornecedor().setVisible(true);
    }//GEN-LAST:event_JmiConsultas_Enderecos_EnderecosFornecedoresActionPerformed

    private void JmiVendas_NovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiVendas_NovaVendaActionPerformed
        new FrmNovaVenda().setVisible(true);
    }//GEN-LAST:event_JmiVendas_NovaVendaActionPerformed

    private void JmiReposicoes_NovaReposicacoDeProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiReposicoes_NovaReposicacoDeProdutosActionPerformed
        new FrmNovaReposicao().setVisible(true);
    }//GEN-LAST:event_JmiReposicoes_NovaReposicacoDeProdutosActionPerformed

    private void JmiFinanceiro_ConsultaDeSaldosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiFinanceiro_ConsultaDeSaldosActionPerformed
        new FrmConsultaDeSaldos().setVisible(true);
    }//GEN-LAST:event_JmiFinanceiro_ConsultaDeSaldosActionPerformed

    private void JmiFinanceiro_ValorAReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiFinanceiro_ValorAReceberActionPerformed
        new FrmConsultaValoresAReceber().setVisible(true);
    }//GEN-LAST:event_JmiFinanceiro_ValorAReceberActionPerformed

    private void JmiFinanceiro_ValoresAPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmiFinanceiro_ValoresAPagarActionPerformed
       new FrmConsultaValoresAPagar().setVisible(true);
    }//GEN-LAST:event_JmiFinanceiro_ValoresAPagarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new FrmEstoque().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JmAjuda;
    private javax.swing.JMenu JmAtendimentos;
    private javax.swing.JMenu JmCadastros;
    private javax.swing.JMenu JmConsultas_Enderecos;
    private javax.swing.JMenu JmEstoque;
    private javax.swing.JMenu JmVendas;
    private javax.swing.JMenuItem JmiAjuda_Sair;
    private javax.swing.JMenuItem JmiAjuda_Sobre;
    private javax.swing.JMenuItem JmiAtendimentos_NovoAtendimento;
    private javax.swing.JMenuItem JmiAtendimentos_NovoTipoAtendimento;
    private javax.swing.JMenuItem JmiCadastros_Clientes_NovoCliente;
    private javax.swing.JMenuItem JmiCadastros_Clientes_NovoEndereco;
    private javax.swing.JMenuItem JmiCadastros_Clientes_NovoPet;
    private javax.swing.JMenuItem JmiCadastros_Fornecedores_NovoEndereco;
    private javax.swing.JMenuItem JmiCadastros_Fornecedores_NovoFornecedor;
    private javax.swing.JMenuItem JmiCadastros_Produtos;
    private javax.swing.JMenuItem JmiConsultas_Atendimentos;
    private javax.swing.JMenuItem JmiConsultas_Clientes;
    private javax.swing.JMenuItem JmiConsultas_Enderecos_EnderecosCliente;
    private javax.swing.JMenuItem JmiConsultas_Enderecos_EnderecosFornecedores;
    private javax.swing.JMenuItem JmiConsultas_Fornecedores;
    private javax.swing.JMenu JmiConsultas_Pets;
    private javax.swing.JMenuItem JmiConsultas_Produtos;
    private javax.swing.JMenuItem JmiConsultas_Vendas;
    private javax.swing.JMenuItem JmiFinanceiro_ConsultaDeSaldos;
    private javax.swing.JMenuItem JmiFinanceiro_ValorAReceber;
    private javax.swing.JMenuItem JmiFinanceiro_ValoresAPagar;
    private javax.swing.JMenuItem JmiPets;
    private javax.swing.JMenuItem JmiReposicoes_NovaReposicacoDeProdutos;
    private javax.swing.JMenuItem JmiVendas_NovaVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
